### ISSUE TITLE
Bug when trying to deploy on vercel

### ISSUE THREAD

**Issue by caducoder** [DIGOARTHUR/github-automated-repos#14]
### Which element(s) are the source of the bug?

Don't known / other

### Description

I got this bug in development, but i fixed changing the main file extension to index.js (was index.ts) in package.json at node_modules. On Vercel I don't know how to proceed. 
![image](https://github.com/DIGOARTHUR/github-automated-repos/assets/73801000/a5f51d0f-e49e-4fb6-b3ff-b5b5b238d1f6)

### Please provide the exception or error you saw

```true
[commonjs--resolver] Failed to resolve entry for package "github-automated-repos". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "github-automated-repos". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-1513d487.js:34405:11)
    at resolvePackageEntry (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-1513d487.js:34402:5)
    at tryNodeResolve (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-1513d487.js:34160:20)
    at Object.resolveId (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-1513d487.js:33962:28)
    at file:///vercel/path0/node_modules/rollup/dist/es/shared/rollup.js:22694:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Command "npm run build" exited with 1
```

**Comment by digoarthur** [comment]
@caducoder  Are you using NextJS?  
My website is hosted on vercel and is working. See the NextJS settings for the package::
[Nextjs config](https://github.com/DIGOARTHUR/github-automated-repos#framework-settings-1)

**Comment by caducoder** [comment]
The problem was I forget the "/index" at `import { useGithubAutomatedRepos, StackIcon, IGithubRepos } from 'github-automated-repos/index';`
Thanks for the tip on linkedin @DIGOARTHUR

**Comment by DIGOARTHUR** [comment]
Happy to have it resolved.

Hug and success!

**Comment by digoarthur** [comment]
Happy to have it resolved.

Hug and success!
