### ISSUE TITLE
doc: (package.json)Change keyword

### ISSUE THREAD

**Issue by digoarthur** [DIGOARTHUR/github-automated-repos#19]
> [!NOTE]
>  ## Improve search through a better keyword, both on GitHub and NPM.

`Suggestion`
- [x] Change `STACK `→  `REACT`

```json

   "keywords": [
        "github",
        "automated",
        "repository",
        "projects",
        "react"
    ]
```

**Comment by adityakalburgi** [comment]
hi @DIGOARTHUR i have fixed this and sent you a pull request can you please merge it?

**Comment by digoarthur** [comment]
Hii, @adityakalburgi . 
I"ll make the commit soon.
Thank so much!!
🚀

**Comment by adityakalburgi** [comment]
Thank you @DIGOARTHUR

**Comment by adityakalburgi** [comment]
Hi, @DIGOARTHUR ,
my pull request is not still merged please do the needfull..
